#ifndef INTERPRETATOR_LIMITS_H
#define INTERPRETATOR_LIMITS_H


constexpr int TABLE_STRING_MAX_SIZE = 1000;
constexpr int TABLE_IDENTIFIER_MAX_SIZE = 1000;
constexpr int TABLE_LABEL_MAX_SIZE = 1000;
constexpr int POLIZ_MAX_SIZE = 1000;
constexpr int SCANNER_BUFFER_MAX_SIZE = 100;


#endif //INTERPRETATOR_LIMITS_H
